name: Format

on: [pull_request]

jobs:
  test:
    name: fmt
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Cache Cargo
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-1

      - name: Run Cargo Fmt
        run: cargo fmt --all -- --check
        env:
          RUST_BACKTRACE: 1
  aggregate:
    name: fmt:required
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: test
    steps:
      - name: Check fmt result
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
